# Site settings
title: Tencent Map
header-img: img/home-bg.jpg
email: aaronguo@tencent.com
copyright_name: Tencent
description: "Tencent Map Github Page"
baseurl: ""
url: "http://tencentmap.github.io"
twitter_username:
github_username:  tencentmap
facebook_username:  
email_username:  aaronguo@tencent.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
